name: Run Telegram Bot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Update Runner
        run: sudo apt-get update
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cancel previous workflow run
        env:
          CANCEL_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          LAST_RUNNER_ID=$(cat ./LAST_RUNNER_ID.txt)
           if [ -n "$CANCEL_TOKEN" ]; then
              curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $CANCEL_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$LAST_RUNNER_ID/cancel"

              echo ${{ github.run_id }} > LAST_RUNNER_ID.txt
           fi
      - name: Commit and push changes
        run: |
          git config --global user.email "ghooch-ali@noreply.com"
          git config --global user.name "ghooch-ali"
          git add .
          git commit -m "last workflow id"
          git push
      # - name: Cancel previous workflow run
      #   env:
      #     CANCEL_TOKEN: ${{ secrets.GH_PAT }}
      #   run: |
      #             if [ -n "$CANCEL_TOKEN" ]; then
      #                PREVIOUS_RUN_ID=$(curl -s -X GET \
      #               -H "Accept: application/vnd.github.v3+json" \
      #               -H "Authorization: Bearer $CANCEL_TOKEN" \
      #               "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=push&status=completed&per_page=2" \
      #               | jq -r '.workflow_runs[1].id')
      #              echo "Previous run ID: $PREVIOUS_RUN_ID"
      #              curl -X POST \
      #             -H "Accept: application/vnd.github.v3+json" \
      #             -H "Authorization: Bearer $CANCEL_TOKEN" \
      #             "https://api.github.com/repos/${{ github.repository }}/actions/runs/$PREVIOUS_RUN_ID/cancel"
      #              fi
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm i

      - name: Run script
        run: node src/index.ts
        env:
          TELEGRAM_BOT_TOEKN: ${{ secrets.TELEGRAM_BOT_TOEKN }}
