name: Run Telegram Bot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Update Runner
        run: sudo apt-get update
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cancel previous workflow run
        env:
          CANCEL_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [ -n "$CANCEL_TOKEN" ]; then
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $CANCEL_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
          fi
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm i

      - name: Run script
        run: node src/index.js
        env:
          TELEGRAM_BOT_TOEKN: ${{ secrets.TELEGRAM_BOT_TOEKN }}
